import cerebellar_stimulation1 from './images/cerebellar_stimulation1.jpg';
import cerebellar_stimulation2 from './images/cerebellar_stimulation2.jpg';
import cerebellar_stimulation3 from './images/cerebellar_stimulation3.jpg';
import cerebellar_stimulation4 from './images/cerebellar_stimulation4.jpg';
import cerebellar_stimulation5 from './images/cerebellar_stimulation5.jpg';
import cerebellar_stimulation6 from './images/cerebellar_stimulation6.jpg';
import cerebellar_stimulation7 from './images/cerebellar_stimulation7.jpg';
import cerebellar_stimulation8 from './images/cerebellar_stimulation8.jpg';
import cerebellar_stimulation9 from './images/cerebellar_stimulation9.jpg';

import interhemispheric_boards1 from './images/interhemispheric_boards1.jpg';
import interhemispheric_boards2 from './images/interhemispheric_boards2.jpg';
import interhemispheric_boards3 from './images/interhemispheric_boards3.jpg';
import interhemispheric_boards4 from './images/interhemispheric_boards4.jpg';
import interhemispheric_boards5 from './images/interhemispheric_boards5.jpg';

import neuro_eights1 from './images/neuro_eights1.jpg';
import neuro_eights2 from './images/neuro_eights2.jpg';
import neuro_eights3 from './images/neuro_eights3.jpg';
import neuro_eights4 from './images/neuro_eights4.jpg';
import neuro_eights5 from './images/neuro_eights5.jpg';
import neuro_eights6 from './images/neuro_eights6.jpg';
import neuro_eights7 from './images/neuro_eights7.jpg';

import kinesio_bags1 from './images/kinesio_bags1.jpg';
import kinesio_bags2 from './images/kinesio_bags2.jpg';
import kinesio_bags3 from './images/kinesio_bags3.jpg';
import kinesio_bags4 from './images/kinesio_bags4.jpg';

import ball_set1 from './images/ball_set1.png';
import ball_set2 from './images/ball_set2.png';
import ball_set3 from './images/ball_set3.png';
import ball_set4 from './images/ball_set4.jpg';
import ball_set5 from './images/ball_set5.png';
import ball_set6 from './images/ball_set6.png';
import ball_set7 from './images/ball_set7.jpg';
import ball_set8 from './images/ball_set8.jpg';
import ball_set9 from './images/ball_set9.jpg';
import ball_set10 from './images/ball_set10.png';
import ball_set11 from './images/ball_set11.jpg';
import ball_set12 from './images/ball_set12.jpg';
import ball_set13 from './images/ball_set13.jpg';
import ball_set14 from './images/ball_set14.jpg';
import ball_set15 from './images/ball_set15.jpg';
import ball_set16 from './images/ball_set16.jpg';
import ball_set17 from './images/ball_set17.png';
import ball_set18 from './images/ball_set18.jpg';
import ball_set19 from './images/ball_set19.jpg';
import ball_set20 from './images/ball_set20.jpg';




let products = [
	// Мозжечковая стимуляция

	{
		id: Math.random(),
		titel: 'Доска Бильгоу для мозжечковой стимуляции',
		information: 'Тренажеров для мозжечковой стимуляции.',
		img: cerebellar_stimulation1,
		price: 2429,
		discount: 28,
		type: ['Акция', 'Товары месяца'],
		productDiscount: 'Акция',
		count: 1,
		productMonth: 'Товары месяца',
		priceTtoal: 2429,
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Комплект "Быстрый старт+"',
		information: 'Комплект тренажеров для развивающих занятий',
		img: cerebellar_stimulation2,
		price: 4750,
		count: 1,
		type: ['Новинка'],
		productNew: 'Новинка',
		priceTtoal: 4750,
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Комплект "Макси"',
		information: 'Комплект тренажеров для развивающих занятий',
		img: cerebellar_stimulation3,
		price: 9490,
		count: 1,
		priceTtoal: 9490,
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Комплект "Успех"',
		information: 'Комплект тренажеров для развивающих занятий',
		img: cerebellar_stimulation4,
		price: 7490,
		priceTtoal: 7490,
		count: 1,
		type: ['Товары месяца'],
		productMonth: 'Товары месяца',
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Мяч-маятник и планка для отбивания с цифрами',
		information: 'Мяч-маятник и планка для отбивания цветная с цифрами',
		img: cerebellar_stimulation5,
		price: 1590,
		priceTtoal: 1590,
		discount: 13,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Мишень напольная цветная',
		information: 'Напольная мишень для развивающих занятий, 46 х 46 см',
		img: cerebellar_stimulation6,
		price: 1590,
		priceTtoal: 1590,
		count: 1,
		type: ['Новинка'],
		productNew: 'Новинка',
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Мишень напольная цветная с цифрами',
		information: 'Напольная мишень для развивающих занятий, 46 х 46 см',
		img: cerebellar_stimulation7,
		price: 1590,
		priceTtoal: 1590,
		count: 1,
		productMonth: 'Товары месяца',
		discount: 8,
		type: ['Акция'],
		productDiscount: 'Акция',
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Мишень напольная цветная с цифрами',
		information: 'Напольная мишень для развивающих занятий, 46 х 46 см',
		img: cerebellar_stimulation8,
		price: 1590,
		priceTtoal: 1590,
		count: 1,
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},
	{
		id: Math.random(),
		titel: 'Стойка с мишенями-целями',
		information: 'Стойка с пятью двусторонними мишенями-целями, высота до 106 см',
		img: cerebellar_stimulation9,
		price: 1900,
		priceTtoal: 1900,
		count: 1,
		inCart: false,
		categori: 'Мозжечковая стимуляция',
	},

	

	// Межполушарные доски

	{
		id: Math.random(),
		titel: 'Межполушарный лабиринт 4 в 1. Базовый набор',
		information: 'Межполушарный лабиринт 4в1: Базовый набор, 450 х 235 мм',
		img: interhemispheric_boards1,
		price: 1690,
		priceTtoal: 1690,
		count: 1,
		type: ['Новинка'],
		productNew: 'Новинка',
		inCart: false,
		categori: 'Межполушарные доски',
	},
	{
		id: Math.random(),
		titel: 'Межполушарный лабиринт 4 в 1. Полный набор',
		information: 'Межполушарный лабиринт 4в1: Полный набор, 450 х 235 мм',
		img: interhemispheric_boards2,
		price: 9490,
		discount: 50,
		type: ['Акция'],
		productDiscount: 'Акция',
		priceTtoal: 9490,
		count: 1,
		inCart: false,
		categori: 'Межполушарные доски',
	},
	{
		id: Math.random(),
		titel: 'Межполушарный лабиринт 4 в 1. Стандартный набор',
		information: 'Межполушарный лабиринт 4в1: Стандартный набор, 450 х 235 мм',
		img: interhemispheric_boards3,
		price: 4690,
		priceTtoal: 4690,
		count: 1,
		inCart: false,
		categori: 'Межполушарные доски',
	},
	{
		id: Math.random(),
		titel: '1 пара карточек для рисования 2 руками',
		information: 'Ламинированные карточки с рисунком, 2 шт, 220х220 мм',
		img: interhemispheric_boards4,
		price: 290,
		priceTtoal: 290,
		count: 1,
		inCart: false,
		categori: 'Межполушарные доски',
	},
	{
		id: Math.random(),
		titel: 'Основа для вкладышей',
		information: 'Основа для вкладышей межполушарного лабиринта, 450 х 235 мм',
		img: interhemispheric_boards5,
		price: 890,
		discount: 10,
		type: ['Акция', 'Товары месяца', 'Новинка'],
		productDiscount: 'Акция',
		priceTtoal: 890,
		count: 1,
		productNew: 'Новинка',
		productMonth: 'Товары месяца',
		inCart: false,
		categori: 'Межполушарные доски',
	},



	// Нейровосьмерки

	{
		id: Math.random(),
		titel: 'Комплект нейровосьмерок',
		information: 'Комплект нейровосьмерок для развивающих занятий, 3 шт',
		img: neuro_eights1,
		price: 1650,
		priceTtoal: 1650,
		count: 1,
		inCart: false,
		categori: 'Нейрокосички',
	},
	{
		id: Math.random(),
		titel: 'Нейровосьмерка',
		information: 'Нейровосьмерка для развивающих занятий, длина 45 см',
		img: neuro_eights2,
		price: 875,
		priceTtoal: 875,
		discount: 38,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		inCart: false,
		categori: 'Нейрокосички',
	},
	{
		id: Math.random(),
		titel: 'Нейровосьмерка Клевер',
		information: 'Нейровосьмерка “Клевер” для развивающих занятий, 47х35 см',
		img: neuro_eights3,
		price: 1350,
		priceTtoal: 1350,
		count: 1,
		type: ['Товары месяца'],
		productMonth: 'Товары месяца',
		inCart: false,
		categori: 'Нейрокосички',
	},
	{
		id: Math.random(),
		titel: 'Суперкомплект Нейровосьмерок 7 шт',
		information: 'Комплект нейровосьмерок для развивающих занятий, 7 шт',
		img: neuro_eights4,
		price: 5990,
		discount: 22,
		type: ['Акция'],
		productDiscount: 'Акция',
		priceTtoal: 5990,
		count: 1,
		inCart: false,
		categori: 'Нейрокосички',
	},
	{
		id: Math.random(),
		titel: 'Нейровосьмерка Кольцевая',
		information: 'Нейровосьмерка Кольцевая для развивающих занятий, длина 55 см',
		img: neuro_eights5,
		price: 1100,
		priceTtoal: 1100,
		count: 1,
		inCart: false,
		categori: 'Нейрокосички',
	},
	{
		id: Math.random(),
		titel: 'Нейрокосичка',
		information: 'Нейрокосичка для развивающих занятий, длина 45 см',
		img: neuro_eights6,
		price: 1150,
		priceTtoal: 1150,
		count: 1,
		inCart: false,
		categori: 'Нейрокосички',
	},
	{
		id: Math.random(),
		titel: 'Нейровосьмерка Квадро',
		information: 'Нейровосьмерка “Квадро” для развивающих занятий, 45х45 см',
		img: neuro_eights7,
		price: 1650,
		discount: 30,
		type: ['Акция'],
		productDiscount: 'Акция',
		priceTtoal: 1650,
		count: 1,
		inCart: false,
		categori: 'Нейровосьмерки',
	},



	// Кинезио мешки

	{
		id: Math.random(),
		titel: 'Кинезиологические мешочки',
		information: 'Кинезиологические мешочки для развивающих упражнений 4 шт',
		img: kinesio_bags1,
		price: 650,
		priceTtoal: 650,
		discount: 18,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		productNew: 'Новинка',
		inCart: false,
		categori: 'Кинезио мешки',
	},
	{
		id: Math.random(),
		titel: 'Сенсорные мешочки Радуга',
		information: 'Комплект сенсорных мешочков для развивающих игр, 7 шт/ 10,5*6см',
		img: kinesio_bags2,
		price: 990,
		count: 1,
		priceTtoal: 990,
		inCart: false,
		categori: 'Кинезио мешки',
	},
	{
		id: Math.random(),
		titel: 'Сенсорные мешочки (парные)',
		information: 'Комплект сенсорных мешочков для развивающих игр, 10 шт/10,5*6см',
		img: kinesio_bags3,
		price: 1190,
		priceTtoal: 1190,
		discount: 25,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		inCart: false,
		categori: 'Кинезио мешки',
	},
	{
		id: Math.random(),
		titel: '3 весовых мешочка с крупой (разный вес)',
		information: 'Комплект весовых мешочков с крупой для развивающих упражнений, 3 шт',
		img: kinesio_bags4,
		price: 550,
		count: 1,
		type: ['Товары месяца'],
		productMonth: 'Товары месяца',
		priceTtoal: 550,
		inCart: false,
		categori: 'Кинезио мешки',
	},



	//Кинезио мячи

	{
		id: Math.random(),
		titel: 'Кинезиологический мяч 2 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 60 мм',
		img: ball_set1,
		price: 1140,
		count: 1,
		priceTtoal: 1140,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Кинезиологический мяч 1 шт',
		information: 'Мяч для развивающих упражнений, диаметр 60 мм',
		img: ball_set2,
		price: 580,
		count: 1,
		priceTtoal: 580,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Набор кинезиомячей Sky Bounce (США) 2 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 50 мм',
		img: ball_set3,
		price: 770,
		priceTtoal: 770,
		count: 1,
		type: ['Товары месяца', 'Новинка'],
		productNew: 'Новинка',
		productMonth: 'Товары месяца',
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Набор мячей: Кинезиологические мячи 2 шт + с фиксацией на одежде 2 шт',
		information: 'Комплект мячей для развивающих упражнений',
		img: ball_set4,
		price: 910,
		priceTtoal: 910,
		discount: 14,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Кинезиомяч Sky Bounce (США) 1 шт',
		information: 'Мяч для развивающих упражнений, диаметр 50 мм',
		img: ball_set5,
		price: 390,
		count: 1,
		priceTtoal: 390,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Кинезиологический мяч 4 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 60 мм',
		img: ball_set6,
		price: 2240,
		priceTtoal: 2240,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мяч для развития реакции 1 шт',
		information: 'Мяч для развития реакции, диаметр 35 мм',
		img: ball_set7,
		price: 490,
		priceTtoal: 490,
		discount: 23,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		productNew: 'Новинка',
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мягкий-мяч маятник (Стресс болл)',
		information: 'Мягкий мяч-маятник для развивающих упражнений, диаметр 55 мм',
		img: ball_set8,
		price: 495,
		priceTtoal: 495,
		discount: 10,
		type: ['Акция'],
		productDiscount: 'Акция',
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мяч-маятник',
		information: 'Мяч-маятник для развивающих упражнений, диаметр 70мм',
		img: ball_set9,
		price: 530,
		priceTtoal: 530,
		count: 1,
		type: ['Товары месяца'],
		productMonth: 'Товары месяца',
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Набор кинезиомячей Sky Bounce (США) 4 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 50 мм',
		img: ball_set10,
		price: 1520,
		discount: 35,
		type: ['Акция'],
		productDiscount: 'Акция',
		priceTtoal: 1520,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мяч с водой 250 гр',
		information: 'Мяч с водой для развивающих упражнений, вес 250 гр',
		img: ball_set11,
		price: 350,
		count: 1,
		priceTtoal: 350,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Комбо набор мячей',
		information: 'Комбо набор мячей: 2 кинезио, 2 с фиксацией, мяч-маятник, мягкий мяч-маятник',
		img: ball_set12,
		price: 1890,
		priceTtoal: 1890,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Кинезиологический мяч 50 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 60 мм',
		img: ball_set13,
		price: 15000,
		priceTtoal: 15000,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мячи с фиксацией на одежде 2 шт',
		information: 'Комплект мячей с фиксацией для развивающих упражнений, диаметр 45 мм',
		img: ball_set14,
		price: 360,
		priceTtoal: 360,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мяч с водой 500 гр',
		information: 'Мяч с водой для развивающих упражнений, вес 500 гр',
		img: ball_set15,
		price: 390,
		count: 1,
		priceTtoal: 390,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Мяч с водой 1000 гр',
		information: 'Мяч с водой для развивающих упражнений, вес 1000 гр',
		img: ball_set16,
		price: 430,
		discount: 40,
		type: ['Акция'],
		productDiscount: 'Акция',
		priceTtoal: 430,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Кинезиологический мяч 10 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 60 мм',
		img: ball_set17,
		price: 5500,
		priceTtoal: 5500,
		count: 1,
		type: ['Товары месяца', 'Новинка'],
		productMonth: 'Товары месяца',
		productNew: 'Новинка',
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Набор мячей для развития реакции 2 шт',
		information: 'Мяч для развития реакции, диаметр 68 мм',
		img: ball_set18,
		price: 790,
		priceTtoal: 790,
		count: 1,
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: '(США) 10 шт Набор кинезиомячей Sky Bounce (США) 10 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 50 мм',
		img: ball_set19,
		price: 3750,
		discount: 17,
		type: ['Акция', 'Новинка'],
		productDiscount: 'Акция',
		priceTtoal: 3750,
		count: 1,
		productNew: 'Новинка',
		inCart: false,
		categori: 'Кинезио мячи',
	},
	{
		id: Math.random(),
		titel: 'Набор кинезиомячей Sky Bounce (США) 50 шт',
		information: 'Комплект мячей для развивающих упражнений, диаметр 50 мм',
		img: ball_set20,
		price: 18500,
		priceTtoal: 18500,
		count: 1,
		type: ['Товары месяца'],
		productMonth: 'Товары месяца',
		inCart: false,
		categori: 'Кинезио мячи',
	},
]

export default products;